/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermeniSiConditiiRouteImport } from './routes/termeni-si-conditii'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiCheckoutSessionRouteImport } from './routes/api/checkout/session'
import { Route as ApiCheckoutOrderStatusRouteImport } from './routes/api/checkout/order-status'
import { Route as ApiCheckoutFulfillRouteImport } from './routes/api/checkout/fulfill'

const TermeniSiConditiiRoute = TermeniSiConditiiRouteImport.update({
  id: '/termeni-si-conditii',
  path: '/termeni-si-conditii',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutSessionRoute = ApiCheckoutSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiCheckoutRoute,
} as any)
const ApiCheckoutOrderStatusRoute = ApiCheckoutOrderStatusRouteImport.update({
  id: '/order-status',
  path: '/order-status',
  getParentRoute: () => ApiCheckoutRoute,
} as any)
const ApiCheckoutFulfillRoute = ApiCheckoutFulfillRouteImport.update({
  id: '/fulfill',
  path: '/fulfill',
  getParentRoute: () => ApiCheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cookies': typeof CookiesRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/menu': typeof MenuRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/checkout/fulfill': typeof ApiCheckoutFulfillRoute
  '/api/checkout/order-status': typeof ApiCheckoutOrderStatusRoute
  '/api/checkout/session': typeof ApiCheckoutSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cookies': typeof CookiesRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/menu': typeof MenuRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/checkout/fulfill': typeof ApiCheckoutFulfillRoute
  '/api/checkout/order-status': typeof ApiCheckoutOrderStatusRoute
  '/api/checkout/session': typeof ApiCheckoutSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cookies': typeof CookiesRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/menu': typeof MenuRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/checkout/fulfill': typeof ApiCheckoutFulfillRoute
  '/api/checkout/order-status': typeof ApiCheckoutOrderStatusRoute
  '/api/checkout/session': typeof ApiCheckoutSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/confidentialitate'
    | '/cookies'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/menu'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termeni-si-conditii'
    | '/api/checkout'
    | '/checkout/success'
    | '/api/checkout/fulfill'
    | '/api/checkout/order-status'
    | '/api/checkout/session'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/confidentialitate'
    | '/cookies'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/menu'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termeni-si-conditii'
    | '/api/checkout'
    | '/checkout/success'
    | '/api/checkout/fulfill'
    | '/api/checkout/order-status'
    | '/api/checkout/session'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/confidentialitate'
    | '/cookies'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/menu'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termeni-si-conditii'
    | '/api/checkout'
    | '/checkout/success'
    | '/api/checkout/fulfill'
    | '/api/checkout/order-status'
    | '/api/checkout/session'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  CookiesRoute: typeof CookiesRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MenuRoute: typeof MenuRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermeniSiConditiiRoute: typeof TermeniSiConditiiRoute
  ApiCheckoutRoute: typeof ApiCheckoutRouteWithChildren
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termeni-si-conditii': {
      id: '/termeni-si-conditii'
      path: '/termeni-si-conditii'
      fullPath: '/termeni-si-conditii'
      preLoaderRoute: typeof TermeniSiConditiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/session': {
      id: '/api/checkout/session'
      path: '/session'
      fullPath: '/api/checkout/session'
      preLoaderRoute: typeof ApiCheckoutSessionRouteImport
      parentRoute: typeof ApiCheckoutRoute
    }
    '/api/checkout/order-status': {
      id: '/api/checkout/order-status'
      path: '/order-status'
      fullPath: '/api/checkout/order-status'
      preLoaderRoute: typeof ApiCheckoutOrderStatusRouteImport
      parentRoute: typeof ApiCheckoutRoute
    }
    '/api/checkout/fulfill': {
      id: '/api/checkout/fulfill'
      path: '/fulfill'
      fullPath: '/api/checkout/fulfill'
      preLoaderRoute: typeof ApiCheckoutFulfillRouteImport
      parentRoute: typeof ApiCheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ApiCheckoutRouteChildren {
  ApiCheckoutFulfillRoute: typeof ApiCheckoutFulfillRoute
  ApiCheckoutOrderStatusRoute: typeof ApiCheckoutOrderStatusRoute
  ApiCheckoutSessionRoute: typeof ApiCheckoutSessionRoute
}

const ApiCheckoutRouteChildren: ApiCheckoutRouteChildren = {
  ApiCheckoutFulfillRoute: ApiCheckoutFulfillRoute,
  ApiCheckoutOrderStatusRoute: ApiCheckoutOrderStatusRoute,
  ApiCheckoutSessionRoute: ApiCheckoutSessionRoute,
}

const ApiCheckoutRouteWithChildren = ApiCheckoutRoute._addFileChildren(
  ApiCheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ConfidentialitateRoute: ConfidentialitateRoute,
  CookiesRoute: CookiesRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MenuRoute: MenuRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermeniSiConditiiRoute: TermeniSiConditiiRoute,
  ApiCheckoutRoute: ApiCheckoutRouteWithChildren,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
